---
- hosts: web
  serial: 1
  become: yes
  become_method: sudo
  #  vars:
  #  package_name: devopsarea-1.0.war

  tasks:
   - name: Install Java
     apt: name=default-jdk state=present

   - name: Install Tomcat
     apt: name=tomcat8 state=present

   - name: Install Tomcat admin
     apt: name=tomcat8-admin state=present

   - name: Configure Tomcat users
     copy:
       src: tomcat-users.xml
       dest: /etc/tomcat8/
       owner: root
       group: tomcat8
       mode: 640

   - name: Stop the firewall
     service:
       name: ufw
       state: stopped

#   - name: restart tomcat
#     service:
#       name: tomcat8
#       state: restarted


#   - name: wait for tomcat to start
#     wait_for: port=8080
#   - name: Adding the healthcheck file
#     copy:
#       src: v1-devopsarea-1.0.war
#       dest: /var/lib/tomcat8/webapps/ROOT/

   - name: deploy the generated package to tomcat
     copy:
       src: ./target/v1-devopsarea-1.0.war
       dest: /var/lib/tomcat8/webapps/
       mode: 0777                                                                                                                                                                              
