apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zein-app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/DevOps-Area/Projects.git
    targetRevision: HEAD
    path: k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
